### ISSUE TITLE
installing ob-ada-spark

### ISSUE THREAD

**Issue by bruno-who-likes** [rocher/ob-ada-spark#2]
Could you please expand on how you are installing this into Emacs? I installed it by adding 
(org-babel-do-load-languages
   'org-babel-load-languages
    '((ada-spark . t))) 
to my config file.  I am able to get C-c C-c to work. I am not able to tangle my code. When I try C-c C-v C-t to tangle the code I get the error "Symbol's function definition is void: time-stamp-string". This is the first third-party language I've used for org-babel so your advice would be much appreciated.

**Comment by bruno-who-likes** [comment]
Just as a follow up. I also installed this through melpa. I was still not able to tangle the code.

**Comment by bruno-who-likes** [comment]
I found the source of the problem and the solution. The function time-stamp-string needs the package time-stamp. To fix this I added (require 'time-stamp) in ob-ada-spark.el.

**Comment by rocher** [comment]
Yes, you're completely right.
What surprises me a lot is that this issue was not detected by any of the filters in Melpa (melpazoid). This is probably because you have a very minimal Emacs configuration (is this the case?). I found that there are some functions from `time-stamp` lib loaded in `ldefs-boot.el`, and somehow `time-stamp-string` is also visible in `ob-ada-spark`.
Anyway, a new version with your fix is now avaialbe (v1.2.5b).
Thank you very much for your feedback!!
